language: groovy
jdk:
- oraclejdk7
- openjdk7
addons:
  sauce_connect:
  - username: $SAUCE_USERNAME
  - access_key: $SAUCE_ACCESS_KEY
before_script:
- npm install -g bower
- bower install
script: ! 'npm install && bower install && ./grailsw refresh-dependencies && ./grailsw test-app unit: && ./grailsw test-app integration: && ./grailsw test-app functional: -Dgeb.env=sauceChromeLinux '
env:
  global:
  - secure: N4EJHKFrkWbuiErvU+3hYJFKCV/DbEvx6ZYs7Y0KUPk6V+1/H7XfXw93KutErdxGbQkfK8mirqaI8sFxYqZbM9HBfBAzez16miLmWRRjOtnHoZH2Xvni8keN/9DY5plK1j5Gyo160xGQ5KplRsvLd6q7FhuYo0Z1IC/7oOne9p8=
  - secure: U3HITe3Vjlg7Mycl/OYVULbUSBrcjO5kilGDPGGlUoMowKyKEVq9ao4uTEXkVj60RQOtt06r1yIu/DkgJtyqPFGocIV4cMFaC8VwTcF+qAOYvoWvnY43Dx7Ur8ya2XSizUyJHZHwRfHEV2vJa0sgFjGokcX0+/FN/b3ktF8x9XQ=
  - secure: NOxM5/DbyHgK2Q6Oc608D4d8hPzQAstigZddiqMrEOnnjsKeLl87DIUu4u8z1bwUivDZeIleBN+l0U1c3BhgTu+NzDd3y1HIVe62DdP1TrQsrUfaO0fBH/Y3HtVTp+tHT0gz0UzB0mXaRULDvuOx0XwQoO+FWqHlr9whwLHi9F0=
branches:
  only:
  - master
  - develop

deploy:
   edge: true
   provider: cloudfoundry
   username: soheil.saifipour@ndm.ox.ac.uk
   password: $DEPLOY_KEY
   api: https://api.run.pivotal.io
   organization: jwatters-org

#deploy:
#  provider: heroku
#  api_key:
#    secure: SiUI5KcYAqf2mFbzdZ0+y5cwEZqHuoiLX2qASJPLTXThamxNWOKeAUZjFuiEcr2s5yEFHV8RBDt8SNttSqNwKwe8xW17pI/BuAXVmWpOR5EyxxEfkXUsFmcRWuXaIGd2YsV2LKbN9ynSf89kF/AM8Ml3EdSRR2s+PXQplFH1AQs=
#  app: modelcatalogueviewer
#  strategy: git
#  on:
#    repo: SoheilSaif/ModelCatalogueViewer
#    branch: develop